server:
  port: 1666
spring:
  application:
    name: configuration-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/wilfredkim/config-repo.git
          #uri: C:\\Users\\User\\Documents\\Workspace\\Tutorials\\2024 Microservices\\config-repo
          timeout: 30





